default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: "app-store",
        teamID: "B3A6AN2HA4",
        signingStyle: "automatic"
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
